name: Build to Nixbuild

on:
  push:
    branches: ["**"]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup nixbuild
        uses: nixbuild/nixbuild-action@v20
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
          generate_summary_for: "workflow"

      - name: Build
        run: |
          nix build \
            --print-build-logs \
            --builders "" \
            --max-jobs 100 \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net \
            --accept-flake-config \
            .#allSystems
