name: Bump flake.lock

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup nixbuild
        uses: nixbuild/nixbuild-action@v20
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
          generate_summary_for: "workflow"

      - name: Update Lockfile
        run: nix flake update

      - name: Build
        run: |
          nix build \
            --print-build-logs \
            --builders "" \
            --max-jobs 100 \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net \
            --accept-flake-config \
            .#allSystems

      - uses: stefanzweifel/git-auto-commit-action@main
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: "--no-verify --signoff"
          file_pattern: flake.lock
          commit_user_name: Flake Bot # defaults to "GitHub Actions"
          #commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: false
          skip_fetch: true
